trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: PlanPhase
    jobs:
      - job: terraformInstallation
        steps:  
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: terrafrom-Init
          inputs:
             provider: 'azurerm'
             command: 'init'
             backendServiceArm: 'Azure Devops(e6787d56-1b3f-4a67-81b3-ed99c2f02315)'
             backendAzureRmOverrideSubscriptionID: 'e6787d56-1b3f-4a67-81b3-ed99c2f02315'
             backendAzureRmResourceGroupName: 'etc-azuredevops-001'
             backendAzureRmStorageAccountName: 'etcstorageaccount001'
             backendAzureRmContainerName: 'tfstate'
             backendAzureRmKey: 'prod.terraform.tfstate'     

        - task: TerraformTask@5
          displayName: Plan-Phase
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'Azure Devops(e6787d56-1b3f-4a67-81b3-ed99c2f02315)'
  
  - stage: Applyphase
    jobs:
      - job: terraformapply
        steps:

        - task: TerraformTask@5
          displayName: Apply-Phase
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'Azure Devops(e6787d56-1b3f-4a67-81b3-ed99c2f02315)'
     