trigger:
branches:
include:
- main

pool:
vmImage: 'ubuntu-latest'

stages:
stage: TerraformInstaller
  displayName: 'Install Terraform'
    jobs:
    - job: TerraformInstaller
       steps:
        - task: TerraformInstaller@1
        - inputs:
          terraformVersion: 'latest'

  stage: TerraformInitAndPlan
  displayName: 'Terraform Init and Plan'
  dependsOn: TerraformInstaller
    jobs:
    - job: TerraformInit
     steps:
     - checkout: self
        - task: TerraformInstaller@1
      inputs:
      terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'Azure Devops'
      backendAzureRmResourceGroupName: 'etc-azuredevops-001'
      backendAzureRmStorageAccountName: 'etcstorageaccount001'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'prod.terraform.tfstate'

    - task: TerraformTask@5
      displayName: 'Terraform Plan'
      inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'Azure Devops'
